version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_SERVER_URL: ${VITE_SERVER_URL}
    image: pco-frontend-image:latest
    container_name: pco-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend

  backend:
    image: pco-backend-image:latest
    container_name: pco-backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SERVER_URL: ${SERVER_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}

      
    networks:
      - frontend
    volumes:
      - /data/backend/local_file_db:/app/local_file_db

networks:
  frontend:
    driver: bridge
